# Generated by Django 4.0.5 on 2026-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_teamuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='chat_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('mattermost', 'Mattermost')], max_length=25),
        ),
    ]
