# Generated by Django 4.0.5 on 2026-03-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_teamuser'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacoledger',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.team'),
        ),
    ]
